//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_Calculatrice {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.TextBox TextArea;
        
        protected System.Web.UI.WebControls.Button button1;
        
        protected System.Web.UI.WebControls.Button button2;
        
        protected System.Web.UI.WebControls.Button button3;
        
        protected System.Web.UI.WebControls.Button button4;
        
        protected System.Web.UI.WebControls.Button button5;
        
        protected System.Web.UI.WebControls.Button button6;
        
        protected System.Web.UI.WebControls.Button button7;
        
        protected System.Web.UI.WebControls.Button button8;
        
        protected System.Web.UI.WebControls.Button button9;
        
        protected System.Web.UI.WebControls.Button buttonPlus;
        
        protected System.Web.UI.WebControls.Button buttonEqual;
        
        protected System.Web.UI.WebControls.Button buttonClear;
    }
}
